version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: xxxx
      POSTGRES_PASSWORD: xxxx
    ports:
      - "5432:5432"
    networks:
      no-touch-networks:
        ipv4_address: 192.168.1.2
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: xxx
      MONGO_INITDB_ROOT_PASSWORD: xxxx
    ports:
      - "27017:27017"
    networks:
      no-touch-networks:
        ipv4_address: 192.168.1.3
  frontend:
    image: juan172/no-touch-front:v1.0
    ports:
      - "80:80"
    networks:
      no-touch-networks:
        ipv4_address: 192.168.1.4
  backend1:
    image: juan172/no-touch-backend1:v1.0
    environment:
      SECRET_KEY : "xxxx"
      JWT_KEY : 'xxx'
      DB_HOST : "xxx"
      DB_PORT : 'x'
      DB_USERNAME : "xxx"
      DB_PASSWORD : "xxx"
      DB_DATABASE : "xxx"
      SERVER_REST : "http://192.168.1.6:5000"
    ports:
      - "5050:5050"
    networks:
      no-touch-networks:
        ipv4_address: 192.168.1.5
  backend2:
    image: juan172/no-touch-backend2:v1.0
    environment:
      SECRET_KEY : "xxxx"
      JWT_KEY : 'xxx'
      MONGO_HOST : "xxx"
      MONGO_PORT : x
      MONGO_USER : "xxx"
      MONGO_PASS : "xxx"
      MONGO_DATABASE : "xxx"
      MOSQUITTO_SERVER : "http://xxxx"
      MOSQUITTO_PORT: xxx
      MOSQUITTO_ALIVE: xxx
    ports:
      - "5000:5000"
    networks:
      no-touch-networks:
        ipv4_address: 192.168.1.6
  chatbot:
    image: juan172/no-touch-microservice-alarm:v1.0
    environment:
      SECRET_KEY : "xxxx"
      SERVER_REST : "http://192.168.1.6:5000"
      MOSQUITTO_SERVER : "http://xxxx"
      MOSQUITTO_PORT: xxx
      MOSQUITTO_ALIVE: xxx
    ports:
      - "5100:3100"
    networks:
      no-touch-networks:
        ipv4_address: 192.168.1.7

networks:
  no-touch-networks:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

volumes:
  mongodb-data:
    driver: local
  postgres-data:
    driver: local